/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 312f24f0b035dd8f53e37339aefad898)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/app");
	}
	interface Env {
		SL_DEPLOY_ENV: string;
		SL_FEATURE_NETWORK_MOTION: string;
		SL_INDEXING_ALLOWED: string;
		SL_ANALYTICS_ENABLED: string;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SL_DEPLOY_ENV" | "SL_FEATURE_NETWORK_MOTION" | "SL_INDEXING_ALLOWED" | "SL_ANALYTICS_ENABLED">> {}
}
