/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 0904232754ff642b4652617fa232cf61)
interface __BaseEnv_Env {
	LEAD_EMAIL: SendEmail;
	TURNSTILE_SECRET: SecretsStoreSecret;
	LEAD_RATE_LIMIT: RateLimit;
	SL_DEPLOY_ENV: string;
	SL_FEATURE_DIRECT_FORM: string;
	SL_LEAD_EMAIL_ENABLED: string;
	SL_FEATURE_NETWORK_MOTION: string;
	SL_FEATURE_WORK_HERO_VIDEO: string;
	SL_FEATURE_WORK_PRODUCTS_GALLERY: string;
	SL_FEATURE_FOUNDER_EXPERIENCE_GALLERY: string;
	SL_INDEXING_ALLOWED: string;
	SL_ANALYTICS_ENABLED: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/app");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SL_DEPLOY_ENV" | "SL_FEATURE_DIRECT_FORM" | "SL_LEAD_EMAIL_ENABLED" | "SL_FEATURE_NETWORK_MOTION" | "SL_FEATURE_WORK_HERO_VIDEO" | "SL_FEATURE_WORK_PRODUCTS_GALLERY" | "SL_FEATURE_FOUNDER_EXPERIENCE_GALLERY" | "SL_INDEXING_ALLOWED" | "SL_ANALYTICS_ENABLED">> {}
}
